id: P009157
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W26176
  title: དབུ་མ
  author: ''
  volumes:
    52381e4ab85a41579b872dcc0c1249e3:
      image_group_id: I5730
      title: ''
      volume_number: 1
      total_pages: 551
      base_file: v001.txt
